apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1 # num of pods running a particular image
  selector:
    matchLabels: # find all pods with label app: event-bus
      app: event-bus
  template: # specify exact config of a pod
    metadata:
      labels:
        app: event-bus
    spec:
      containers: # '-' is array in yaml
        - name: event-bus
          image: ercecan/event-bus:latest # if version empty also assumed latest
--- # to create multiple objects inside of a single yaml file we add ---
apiVersion: v1
kind: Service # clusterIP service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  type: ClusterIP # optional, kubernetes is default to create ClusterIP service
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
