apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector: # in posts-depl yaml it selects label with app: posts
    app: posts
  ports:
    - name: posts # name can be wahtever you want usually given after app name
      protocol: TCP
      port: 4000
      targetPort: 4000
