apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1 # num of pods running a particular image
  selector:
    matchLabels: # find all pods with label app: query
      app: query
  template: # specify exact config of a pod
    metadata:
      labels:
        app: query
    spec:
      containers: # '-' is array in yaml
        - name: query
          image: ercecan/query:latest # if version empty also assumed latest
--- # to create multiple objects inside of a single yaml file we add ---
apiVersion: v1
kind: Service # clusterIP service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  type: ClusterIP # optional, kubernetes is default to create ClusterIP service
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
